export const SIGN_UP_PLAYER = "SIGN_UP_PLAYER";

export const LOG_IN_PLAYER = "LOG_IN_PLAYER";

export const LOG_OUT_PLAYER = "LOG_OUT_PLAYER";

export const SIGN_UP_PLAYER_ERROR = "SIGN_UP_PLAYER_ERROR";

export const LOG_IN_PLAYER_ERROR = "LOG_IN_PLAYER_ERROR";
